name: MuteMan
main: sp.bukkit.muteman.MuteMan
version: 0.1
commands:
   mute:
      description:
      permission: 
      usage:
   unmute:
      description:
      permission: 
      usage:
   mymute:
      description:
      permission: 
      usage:
   reloadmute:
      description:
      permission: 
      usage:
   getmute:
      description:
      permission: 
      usage:
     